config/routes.rb
Events::Application.routes.draw do
  root "events#index"
  get "events" => "events#index"
  get "events/:id" => "events#show", as: "event"

end

app/models/event.rb
class Event < ActiveRecord::Base
	def free?
		self.price.blank? || self.price.zero?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@time = Time.now
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def format_price(event)
		if event.free?
			content_tag(:strong, "Free!")
		else
			number_to_currency(event.price)
		end
	end

	def format_date(event)
		if !event.starts_at.nil?
			event.starts_at
		else
			"N/A"
		end
	end
end

app/views/events/index.html.erb
<h1><%= pluralize(@events.size, 'Event') %> </h1>

<ul>
	<% @events.each do |event| %>
		<li>
			<strong><%= link_to(event.name, event_path(event)) %></strong>
			in <%= event.location %>: 

			<%= format_price(event) %>
			<br />
			About: <%= truncate(event.description, length: 15) %>
			<br />
			When it starts: <%= format_date(event) %>
		</li>
	<% end %>
</ul>

app/views/events/show.html.erb
<strong><%= @event.name %></strong>
in <%= @event.location %>: 

<%= format_price(@event) %>
<br />
About: <%= truncate(@event.description, length: 15) %>
<br />
When it starts: <%= format_date(@event) %>



<%= link_to "ALl Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>